export const E2EE_ATTACHMENT_MULTIPART_ENCRYPTION_PROGRESS_WEIGHT = 35;
export const E2EE_ATTACHMENT_MULTIPART_UPLOAD_PROGRESS_WEIGHT = 65;
export const E2EE_ATTACHMENT_ORIGINAL_PROGRESS_START = 10;
export const E2EE_ATTACHMENT_ORIGINAL_PROGRESS_END = 95;
