import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  coreSdkSidebar: [{type: 'autogenerated', dirName: 'core-sdk'}],
  reactSdkSidebar: [{type: 'autogenerated', dirName: 'react'}],
};

export default sidebars;
