name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'apps/docs/**' # Chỉ trigger khi có thay đổi trong thư mục docs

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build docs
        run: yarn workspace apps-docs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/docs/build
          publish_branch: gh-pages
